# Listen on 8080 instead of the default 80
Listen 8080

# These are typical defaults; we don't need NameVirtualHost in modern Apache
<IfModule ssl_module>
    Listen 8443
</IfModule>

<IfModule mod_gnutls.c>
    Listen 8443
</IfModule>
